
title: "Left-like Blog"
description: "A minimal blog styled like a Linux text editor window"
url: ""  # set to your GitHub Pages URL if you have one
baseurl: ""  # e.g. /repo-name if using a project site
markdown: kramdown
permalink: /blog/:title/
collections:
  posts:
    output: true
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: false
      author: "Admin"
      image_style: "float-right"
