
title: "Left-like Blog"
description: "A minimal blog styled like a Linux text editor window"
url: "https://pigeonpious.github.io"
baseurl: "/page"
markdown: kramdown
permalink: /blog/:title/
collections:
  posts:
    output: true
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "Admin"
