[build]
  command = "echo 'Static site, no build needed'"
  publish = "."
  functions = "functions"

[dev]
  command = "echo 'Local development'"
  port = 8888

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
  condition = {Role = ["admin"]}

[[redirects]]
  from = "/editor.html"
  to = "/editor.html"
  status = 200
  condition = {Role = ["admin"]}

[[redirects]]
  from = "/drafts.html" 
  to = "/drafts.html"
  status = 200
  condition = {Role = ["admin"]}

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/editor.html"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/drafts.html"
  [headers.values]
    X-Frame-Options = "DENY" 
    X-XSS-Protection = "1; mode=block"
