[build]
  command = "echo 'Static site, no build needed'"
  publish = "."
  functions = "functions"

[dev]
  command = "echo 'Local development'"
  port = 8888

# Authentication handled via cookies and GitHub OAuth

[[headers]]
  for = "/editor.html"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/drafts.html"
  [headers.values]
    X-Frame-Options = "DENY" 
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
